//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CUS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CUS : DbContext
    {
        public CUS()
            : base("name=CUS")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUserRoles> AspNetUserRoles { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<UnidadAfiliacion> UnidadAfiliacion { get; set; }
        public virtual DbSet<Paciente> Paciente { get; set; }
        public virtual DbSet<hc_antecedentes_desarrollo> hc_antecedentes_desarrollo { get; set; }
        public virtual DbSet<hc_antecedentes_ginecoobstetricos> hc_antecedentes_ginecoobstetricos { get; set; }
        public virtual DbSet<hc_antecedentes_perinatales> hc_antecedentes_perinatales { get; set; }
        public virtual DbSet<hc_evaluacion_economica> hc_evaluacion_economica { get; set; }
        public virtual DbSet<hc_evaluacion_social> hc_evaluacion_social { get; set; }
        public virtual DbSet<hc_factores_riesgo_psicologicos> hc_factores_riesgo_psicologicos { get; set; }
        public virtual DbSet<hc_ficha_identificacion> hc_ficha_identificacion { get; set; }
        public virtual DbSet<hc_habitos> hc_habitos { get; set; }
        public virtual DbSet<hc_historial_consumo> hc_historial_consumo { get; set; }
        public virtual DbSet<hc_inmunizaciones> hc_inmunizaciones { get; set; }
        public virtual DbSet<hc_valoracion_familiar> hc_valoracion_familiar { get; set; }
        public virtual DbSet<hc_valores_creencias> hc_valores_creencias { get; set; }
        public virtual DbSet<HistoriaClinica> HistoriaClinica { get; set; }
        public virtual DbSet<hc_alimentacion> hc_alimentacion { get; set; }
        public virtual DbSet<hc_antecedentes_patologicos> hc_antecedentes_patologicos { get; set; }
        public virtual DbSet<hc_interrogatorio> hc_interrogatorio { get; set; }
        public virtual DbSet<hc_riesgo_caidas> hc_riesgo_caidas { get; set; }
        public virtual DbSet<hc_exploracion_fisica> hc_exploracion_fisica { get; set; }
    }
}
