//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CUS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diagnosticos
    {
        public int id { get; set; }
        public string clave { get; set; }
        public string diagnostico { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> nivel { get; set; }
    }
}
