//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CUS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hc_antecedentes_perinatales
    {
        public int Id { get; set; }
        public Nullable<int> NumeroEmbarazo { get; set; }
        public string EnfermedadEmbarazo { get; set; }
        public string EspecifiqueEnfermedadEmbarazo { get; set; }
        public string TratamientoEmbarazo { get; set; }
        public string EspecifiqueTratamientoEmbarazo { get; set; }
        public string LugarParto { get; set; }
        public string EspecifiqueLugarParto { get; set; }
        public string EdadGestional { get; set; }
        public string EspecifiqueEdadGestional { get; set; }
        public string Apgar { get; set; }
        public string EspecifiqueApgar { get; set; }
        public string TipoParto { get; set; }
        public string PartoFue { get; set; }
        public string EspecifiquePartoFue { get; set; }
        public string EspecifiqueMotivoCesarea { get; set; }
        public string ComplicacionObs { get; set; }
        public string EspecifiqueComplicacionObs { get; set; }
        public string TamizMetabolico { get; set; }
        public string TamizMetabolicoOpciones { get; set; }
        public string TamizAuditivo { get; set; }
        public string TamizAuditivoOpciones { get; set; }
        public int Id_Paciente { get; set; }
        public Nullable<int> Id_HistoriaClinica { get; set; }
        public string Clave_hc_px { get; set; }
    
        public virtual Paciente Paciente { get; set; }
    }
}
