//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CUS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hc_antecedentes_patologicos
    {
        public int Id { get; set; }
        public string Antecedentes { get; set; }
        public string PxHospitalizado { get; set; }
        public string EspecifiqueHospitalizado { get; set; }
        public string RealizadoCirugia { get; set; }
        public string EspecifiqueCirugia { get; set; }
        public int Id_Paciente { get; set; }
        public Nullable<bool> CheckRespiratorios { get; set; }
        public Nullable<bool> CheckEndocrinologicos { get; set; }
        public Nullable<bool> CheckCardiovasculares { get; set; }
        public Nullable<bool> CheckOncologicos { get; set; }
        public Nullable<bool> CheckSaludMental { get; set; }
        public Nullable<bool> CheckNeurologicos { get; set; }
        public Nullable<bool> CheckInfectoContagiosos { get; set; }
        public Nullable<bool> CheckProblemasAparatoR { get; set; }
        public Nullable<bool> CheckProblemasGastro { get; set; }
        public Nullable<bool> CheckReumatologicos { get; set; }
        public Nullable<bool> CheckNinguna { get; set; }
        public Nullable<int> Id_HistoriaClinica { get; set; }
        public string Clave_hc_px { get; set; }
    
        public virtual Paciente Paciente { get; set; }
    }
}
