//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CUS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hc_alimentacion
    {
        public int Id { get; set; }
        public string TipoLactancia { get; set; }
        public string TiempoLactancia { get; set; }
        public string EdadAblactacion { get; set; }
        public string AlimentosInicio { get; set; }
        public string EdadIntegracion { get; set; }
        public int Id_Paciente { get; set; }
        public Nullable<int> Id_HistoriaClinica { get; set; }
        public string Clave_hc_px { get; set; }
    
        public virtual Paciente Paciente { get; set; }
    }
}
