//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CUS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hc_evaluacion_social
    {
        public int Id { get; set; }
        public string estadocivil { get; set; }
        public string numeropersonas { get; set; }
        public Nullable<int> numerohabitaciones { get; set; }
        public string hacinamiento { get; set; }
        public string escolaridad { get; set; }
        public string GradoEsc { get; set; }
        public string PromedioEsc { get; set; }
        public string reprobado { get; set; }
        public string EspecifiqueReprobado { get; set; }
        public string Desercion { get; set; }
        public string Guarderia { get; set; }
        public string Cuidador { get; set; }
        public string Problemas { get; set; }
        public string ProblemasMaestros { get; set; }
        public string Ocupacio { get; set; }
        public string TipoTrab { get; set; }
        public string RiesgoSos { get; set; }
        public int Id_Paciente { get; set; }
        public string ServicioSal { get; set; }
        public Nullable<int> Id_HistoriaClinica { get; set; }
        public string Clave_hc_px { get; set; }
    
        public virtual Paciente Paciente { get; set; }
    }
}
