//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CUS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hc_exploracion_fisica
    {
        public int Id { get; set; }
        public Nullable<bool> Check_Craneo_Si { get; set; }
        public Nullable<bool> Check_Craneo_No { get; set; }
        public Nullable<bool> Check_Craneo_Diferido { get; set; }
        public string Describir_Hallazgos_Craneo { get; set; }
        public Nullable<bool> Check_Cara_Si { get; set; }
        public Nullable<bool> Check_Cara_No { get; set; }
        public Nullable<bool> Check_Cara_Diferido { get; set; }
        public string Describir_Hallazgos_Cara { get; set; }
        public Nullable<bool> Check_Ojos_Si { get; set; }
        public Nullable<bool> Check_Ojos_No { get; set; }
        public Nullable<bool> Check_Ojos_Diferido { get; set; }
        public string Describir_Hallazgos_Ojos { get; set; }
        public Nullable<bool> Check_Nariz_Si { get; set; }
        public Nullable<bool> Check_Nariz_No { get; set; }
        public Nullable<bool> Check_Nariz_Diferido { get; set; }
        public string Describir_Hallazgos_Nariz { get; set; }
        public Nullable<bool> Check_Oidos_Si { get; set; }
        public Nullable<bool> Check_Oidos_No { get; set; }
        public Nullable<bool> Check_Oidos_Diferido { get; set; }
        public string Describir_Hallazgos_Oidos { get; set; }
        public Nullable<bool> Check_Boca_Si { get; set; }
        public Nullable<bool> Check_Boca_No { get; set; }
        public Nullable<bool> Check_Boca_Diferido { get; set; }
        public string Describir_Hallazgos_Boca { get; set; }
        public Nullable<bool> Check_Faringe_Si { get; set; }
        public Nullable<bool> Check_Faringe_No { get; set; }
        public Nullable<bool> Check_Faringe_Diferido { get; set; }
        public string Describir_Hallazgos_Faringe { get; set; }
        public Nullable<bool> Check_Cuello_Si { get; set; }
        public Nullable<bool> Check_Cuello_No { get; set; }
        public Nullable<bool> Check_Cuello_Diferido { get; set; }
        public string Describir_Hallazgos_Cuello { get; set; }
        public Nullable<bool> Check_Torax_Si { get; set; }
        public Nullable<bool> Check_Torax_No { get; set; }
        public Nullable<bool> Check_Torax_Diferido { get; set; }
        public string Describir_Hallazgos_Torax { get; set; }
        public Nullable<bool> Check_AparatoR_Si { get; set; }
        public Nullable<bool> Check_AparatoR_No { get; set; }
        public Nullable<bool> Check_AparatoR_Diferido { get; set; }
        public string Describir_Hallazgos_AparatoR { get; set; }
        public Nullable<bool> Check_AparatoC_Si { get; set; }
        public Nullable<bool> Check_AparatoC_No { get; set; }
        public Nullable<bool> Check_AparatoC_Diferido { get; set; }
        public string Describir_Hallazgos_AparatoC { get; set; }
        public Nullable<bool> Check_Abdomen_Si { get; set; }
        public Nullable<bool> Check_Abdomen_No { get; set; }
        public Nullable<bool> Check_Abdomen_Diferido { get; set; }
        public string Describir_Hallazgos_Abdomen { get; set; }
        public Nullable<bool> Check_Genitales_Si { get; set; }
        public Nullable<bool> Check_Genitales_No { get; set; }
        public Nullable<bool> Check_Genitales_Diferido { get; set; }
        public string Describir_Hallazgos_Genitales { get; set; }
        public Nullable<bool> Check_Extremidades_Si { get; set; }
        public Nullable<bool> Check_Extremidades_No { get; set; }
        public Nullable<bool> Check_Extremidades_Diferido { get; set; }
        public string Describir_Hallazgos_Extremidades { get; set; }
        public Nullable<bool> Check_SistemaN_Si { get; set; }
        public Nullable<bool> Check_SistemaN_No { get; set; }
        public Nullable<bool> Check_SistemaN_Diferido { get; set; }
        public string Describir_Hallazgos_SistemaN { get; set; }
        public Nullable<bool> Check_pielYanexos_Diferido { get; set; }
        public string Describir_Hallazgos_pielYanexos { get; set; }
        public Nullable<int> Id_HistoriaClinica { get; set; }
        public string Clave_hc_px { get; set; }
        public int Id_Paciente { get; set; }
        public Nullable<bool> Check_pielanexos_Si { get; set; }
        public Nullable<bool> Check_pielanexos_No { get; set; }
    
        public virtual Paciente Paciente { get; set; }
    }
}
