//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CUS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hc_factores_riesgo_psicologicos
    {
        public int Id { get; set; }
        public string CambiosSueño { get; set; }
        public string CambiosEnergia { get; set; }
        public string CambiosApetito { get; set; }
        public string Pesimismo { get; set; }
        public string Irritabilidad { get; set; }
        public string PerdidaPlacer { get; set; }
        public string PalpitacionesFuertes { get; set; }
        public string SensacionAahogo { get; set; }
        public string MiedoPreocupacion { get; set; }
        public string IdeacionSuicida { get; set; }
        public int Id_Paciente { get; set; }
        public Nullable<int> Id_HistoriaClinica { get; set; }
        public string Clave_hc_px { get; set; }
    
        public virtual Paciente Paciente { get; set; }
    }
}
