//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CUS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hc_habitos
    {
        public int Id { get; set; }
        public string HorasSueño { get; set; }
        public string TieneInsomnio { get; set; }
        public string TieneEnuresis { get; set; }
        public string TienePesadillas { get; set; }
        public string HorasOcio { get; set; }
        public string ActividadFisica { get; set; }
        public string TiempoActividadFisica { get; set; }
        public string FrecuenciaActividadFisica { get; set; }
        public int Id_Paciente { get; set; }
        public Nullable<bool> Check_Adicciones_Padre { get; set; }
        public Nullable<bool> Check_Adicciones_Madre { get; set; }
        public Nullable<bool> Check_Adicciones_Ambas { get; set; }
        public Nullable<bool> Check_Adicciones_NA { get; set; }
        public Nullable<bool> Check_Cardiopatia_Padre { get; set; }
        public Nullable<bool> Check_Cardiopatia_Madre { get; set; }
        public Nullable<bool> Check_Cardiopatia_Ambas { get; set; }
        public Nullable<bool> Check_Cardiopatia_NA { get; set; }
        public Nullable<bool> Check_Diabetes_Padre { get; set; }
        public Nullable<bool> Check_Diabetes_Madre { get; set; }
        public Nullable<bool> Check_Diabetes_Ambas { get; set; }
        public Nullable<bool> Check_Diabetes_NA { get; set; }
        public Nullable<bool> Check_Dislipidemias_Padre { get; set; }
        public Nullable<bool> Check_Dislipidemias_Madre { get; set; }
        public Nullable<bool> Check_Dislipidemias_Ambas { get; set; }
        public Nullable<bool> Check_Dislipidemias_NA { get; set; }
        public Nullable<bool> Check_Epilepsia_Padre { get; set; }
        public Nullable<bool> Check_Epilepsia_Madre { get; set; }
        public Nullable<bool> Check_Epilepsia_Ambas { get; set; }
        public Nullable<bool> Check_Epilepsia_NA { get; set; }
        public Nullable<bool> Check_Hipertension_Padre { get; set; }
        public Nullable<bool> Check_Hipertension_Madre { get; set; }
        public Nullable<bool> Check_Hipertension_Ambas { get; set; }
        public Nullable<bool> Check_Hipertension_NA { get; set; }
        public Nullable<bool> Check_Infectocontagiosas_Padre { get; set; }
        public Nullable<bool> Check_Infectocontagiosas_Madre { get; set; }
        public Nullable<bool> Check_Infectocontagiosas_Ambas { get; set; }
        public Nullable<bool> Check_Infectocontagiosas_NA { get; set; }
        public Nullable<bool> Check_Malformaciones_Padre { get; set; }
        public Nullable<bool> Check_Malformaciones_Madre { get; set; }
        public Nullable<bool> Check_Malformaciones_Ambas { get; set; }
        public Nullable<bool> Check_Malformaciones_NA { get; set; }
        public Nullable<bool> Check_Nefropatias_Padre { get; set; }
        public Nullable<bool> Check_Nefropatias_Madre { get; set; }
        public Nullable<bool> Check_Nefropatias_Ambas { get; set; }
        public Nullable<bool> Check_Nefropatias_NA { get; set; }
        public Nullable<bool> Check_Obesidad_Padre { get; set; }
        public Nullable<bool> Check_Obesidad_Madre { get; set; }
        public Nullable<bool> Check_Obesidad_Ambas { get; set; }
        public Nullable<bool> Check_Obesidad_NA { get; set; }
        public Nullable<bool> Check_Oncologicos_Padre { get; set; }
        public Nullable<bool> Check_Oncologicos_Madre { get; set; }
        public Nullable<bool> Check_Oncologicos_Ambas { get; set; }
        public Nullable<bool> Check_Oncologicos_NA { get; set; }
        public Nullable<int> Id_HistoriaClinica { get; set; }
        public string Clave_hc_px { get; set; }
    
        public virtual Paciente Paciente { get; set; }
    }
}
