//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CUS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hc_interrogatorio
    {
        //
        public int Id { get; set; }
        public Nullable<bool> Check_SintomasG_Si { get; set; }
        public Nullable<bool> Check_SintomasG_No { get; set; }
        public string Describir_SintomasG { get; set; }
        public Nullable<bool> Check_Respiratorio_Si { get; set; }
        public Nullable<bool> Check_Respiratorio_No { get; set; }
        public string Describir_Respiratorio { get; set; }
        public Nullable<bool> Check_Neurologico_Si { get; set; }
        public Nullable<bool> Check_Neurologico_No { get; set; }
        public string Describir_Neurologico { get; set; }
        public Nullable<bool> Check_pielYanexos_Si { get; set; }
        public Nullable<bool> Check_pielYanexos_No { get; set; }
        public string Describir_pielYanexos { get; set; }
        public Nullable<bool> Check_Hematologico_Si { get; set; }
        public Nullable<bool> Check_Hematologico_No { get; set; }
        public string Describir_Hematologico { get; set; }
        public Nullable<bool> Check_Digestivo_Si { get; set; }
        public Nullable<bool> Check_Digestivo_No { get; set; }
        public string Describir_Digestivo { get; set; }
        public Nullable<bool> Check_Genitourinario_Si { get; set; }
        public Nullable<bool> Check_Genitourinario_No { get; set; }
        public string Describir_Genitourinario { get; set; }
        public Nullable<bool> Check_Cardiovascular_Si { get; set; }
        public Nullable<bool> Check_Cardiovascular_No { get; set; }
        public string Describir_Cardiovascular { get; set; }
        public Nullable<bool> Check_Musculoesqueletico_Si { get; set; }
        public Nullable<bool> Check_Musculoesqueletico_No { get; set; }
        public string Describir_Musculoesqueletico { get; set; }
        public Nullable<bool> Check_Renal_Si { get; set; }
        public Nullable<bool> Check_Renal_No { get; set; }
        public string Describir_Renal { get; set; }
        public Nullable<bool> Check_Inmune_Si { get; set; }
        public Nullable<bool> Check_Inmune_No { get; set; }
        public string Describir_Inmune { get; set; }
        public Nullable<int> Id_HistoriaClinica { get; set; }
        public string Clave_hc_px { get; set; }
        public int Id_Paciente { get; set; }
    
        public virtual Paciente Paciente { get; set; }
    }
}
