//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CUS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hc_MED_AntecedentesDes
    {
        public int Id { get; set; }
        public string SostuvoCabeza { get; set; }
        public string Especifica_SostuvoCab { get; set; }
        public string SeSento { get; set; }
        public string Especifica_SeSento { get; set; }
        public string Camino { get; set; }
        public string Especifica_Camino { get; set; }
        public string Habla { get; set; }
        public string Especifica_Habla { get; set; }
        public string ControlEsfinteres { get; set; }
        public string Especifica_ControlEsfin { get; set; }
        public string PruebaEDI { get; set; }
        public string Especifica_PruebaEDI { get; set; }
        public int Id_Paciente { get; set; }
        public string Clave_hc_px { get; set; }
    }
}
