//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CUS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hc_MED_AntecedentesGinecoObs
    {
        public int Id { get; set; }
        public string Menarquia { get; set; }
        public string Motivo_Menarquia { get; set; }
        public string Ritmo_Menarquia { get; set; }
        public string Tipo_Menarquia { get; set; }
        public string Cantidad_Menarquia { get; set; }
        public string Coloracion_Menarquia { get; set; }
        public string Especifica_Coloracion { get; set; }
        public string FenomenosAsoc { get; set; }
        public string DolorPelvico { get; set; }
        public string SangradoAnormal { get; set; }
        public string UltimoMetodoAnti { get; set; }
        public string Especifica_UltimoMetodoAnti { get; set; }
        public string SangradoPostcoito { get; set; }
        public string FlujoTransvaginal { get; set; }
        public string Gesta { get; set; }
        public string Partos { get; set; }
        public string Especifica_Partos { get; set; }
        public string Cesarea { get; set; }
        public string Especifica_Cesarea { get; set; }
        public string Abortos { get; set; }
        public string Especifica_Abortos { get; set; }
        public string HijosTerminos { get; set; }
        public string Especifica_HijosTerminos { get; set; }
        public string Prematuros { get; set; }
        public string Especifica_Prematuros { get; set; }
        public string FechaUltimoParto { get; set; }
        public Nullable<System.DateTime> Especifica_FechaUltimoParto { get; set; }
        public string FechaUltimaCesarea { get; set; }
        public Nullable<System.DateTime> Especifica_FechaUltimaCesarea { get; set; }
        public string Motivo_FechaUltimaCesarea { get; set; }
        public string FechaUltimoAborto { get; set; }
        public Nullable<System.DateTime> Especifica_FechaUltimoAborto { get; set; }
        public string FechaUltimaMenstruacion { get; set; }
        public Nullable<System.DateTime> Especifica_FechaUltimaMenstruacion { get; set; }
        public string FechaProbableParto { get; set; }
        public Nullable<System.DateTime> Especifica_FechaProbableParto { get; set; }
        public string FechaUltimoPapanicolau { get; set; }
        public Nullable<System.DateTime> Especifica_FechaUltimoPapanicolau { get; set; }
        public Nullable<bool> NoRecuerda_FechaUltimoPapanicolau { get; set; }
        public string Resultado_FechaUltimoPapanicolau { get; set; }
        public int Id_Paciente { get; set; }
        public string Clave_hc_px { get; set; }
    }
}
