//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CUS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hc_MED_AntecedentesPeri
    {
        public int Id { get; set; }
        public Nullable<int> NumeroEmbarazo { get; set; }
        public string EnfermedadesEmbarazo { get; set; }
        public string Especifica_EnfermedadesEmb { get; set; }
        public string TratamientosEmbarazo { get; set; }
        public string Especifica_TratamientosEmb { get; set; }
        public string LugarParto { get; set; }
        public string Otra_LugarParto { get; set; }
        public string EdadGestional { get; set; }
        public string Especifica_EdadGes { get; set; }
        public string Apgar { get; set; }
        public string Especifica_Apgar { get; set; }
        public string TipoParto { get; set; }
        public string PartoFue_TipoParto { get; set; }
        public string Distocica_TipoParto { get; set; }
        public string Cesaria_TipoParto { get; set; }
        public string ComplicacionAtenObst { get; set; }
        public string Especifica_Complicacion { get; set; }
        public string TamizMetabolico { get; set; }
        public string Seleccione_TamizMetabolico { get; set; }
        public string TamizAuditivo { get; set; }
        public string Seleccione_TamizAuditivo { get; set; }
        public int Id_Paciente { get; set; }
        public string Clave_hc_px { get; set; }
    }
}
