//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CUS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HC_Medicina : DbContext
    {
        public HC_Medicina()
            : base("name=HC_Medicina")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<hc_MED_Alimentacion> hc_MED_Alimentacion { get; set; }
        public virtual DbSet<hc_MED_AntecedentesDes> hc_MED_AntecedentesDes { get; set; }
        public virtual DbSet<hc_MED_AntecedentesGinecoObs> hc_MED_AntecedentesGinecoObs { get; set; }
        public virtual DbSet<hc_MED_AntecedentesPeri> hc_MED_AntecedentesPeri { get; set; }
        public virtual DbSet<hc_MED_AntecedentesVidaSex> hc_MED_AntecedentesVidaSex { get; set; }
        public virtual DbSet<hc_MED_Habitos> hc_MED_Habitos { get; set; }
        public virtual DbSet<hc_MED_HabitosAlimentacion> hc_MED_HabitosAlimentacion { get; set; }
        public virtual DbSet<hc_MED_HabitusExterior> hc_MED_HabitusExterior { get; set; }
        public virtual DbSet<hc_MED_Inmunizaciones> hc_MED_Inmunizaciones { get; set; }
        public virtual DbSet<hc_MED_Otros> hc_MED_Otros { get; set; }
        public virtual DbSet<hc_MED_Plan> hc_MED_Plan { get; set; }
        public virtual DbSet<hc_MED_PrincipioEvolEstado> hc_MED_PrincipioEvolEstado { get; set; }
        public virtual DbSet<hc_MED_Pronostico> hc_MED_Pronostico { get; set; }
        public virtual DbSet<hc_MED_ResultadosLaboratorio> hc_MED_ResultadosLaboratorio { get; set; }
        public virtual DbSet<hc_PS_AreasAtencion> hc_PS_AreasAtencion { get; set; }
        public virtual DbSet<hc_PS_AtencionPsicologica> hc_PS_AtencionPsicologica { get; set; }
        public virtual DbSet<hc_PS_Familia> hc_PS_Familia { get; set; }
        public virtual DbSet<hc_PS_IndicacionTerapeutica> hc_PS_IndicacionTerapeutica { get; set; }
        public virtual DbSet<hc_PS_MotivoConsulta> hc_PS_MotivoConsulta { get; set; }
        public virtual DbSet<hc_PS_SignosAlarma> hc_PS_SignosAlarma { get; set; }
        public virtual DbSet<hc_PS_SintomatologiaActual> hc_PS_SintomatologiaActual { get; set; }
        public virtual DbSet<hc_MED_ImpresionDiag> hc_MED_ImpresionDiag { get; set; }
    }
}
