//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CUS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hc_MED_Habitos
    {
        public int Id { get; set; }
        public string HorasSuenio { get; set; }
        public string TieneInsomnio { get; set; }
        public string TieneEuresis { get; set; }
        public string TienePesadillas { get; set; }
        public string HorasOcio { get; set; }
        public string ActividadFisica { get; set; }
        public string ActFi_Tiempo { get; set; }
        public string ActFi_Frecuencia { get; set; }
        public int Id_Paciente { get; set; }
        public string Clave_hc_px { get; set; }
    }
}
