//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CUS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hc_MED_HabitusExterior
    {
        public int Id { get; set; }
        public string BuenEstadoGral { get; set; }
        public string Tranquilo { get; set; }
        public string Cooperador { get; set; }
        public string Orientado { get; set; }
        public string FaciesCaract { get; set; }
        public string Depresivo { get; set; }
        public string Ansioso { get; set; }
        public string Agresivo { get; set; }
        public string Temeroso { get; set; }
        public string Irritable { get; set; }
        public string Marcha { get; set; }
        public int Id_Paciente { get; set; }
        public string Clave_hc_px { get; set; }
    }
}
