//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CUS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hc_NUT_EducacionInicial
    {
        public int Id { get; set; }
        public Nullable<bool> CriteriosGen { get; set; }
        public Nullable<bool> PrevencionEnf { get; set; }
        public Nullable<bool> EducacionMat { get; set; }
        public Nullable<bool> PlanificacionDis { get; set; }
        public Nullable<bool> AdopcionPat { get; set; }
        public Nullable<bool> EducacionMej { get; set; }
        public Nullable<bool> EjercicioAd { get; set; }
        public Nullable<bool> EducacionRel { get; set; }
        public Nullable<bool> AdherenciaTrat { get; set; }
        public Nullable<bool> DudasInq { get; set; }
        public Nullable<bool> Oral { get; set; }
        public Nullable<bool> Escrito { get; set; }
        public Nullable<bool> Video { get; set; }
        public Nullable<bool> Demostracion { get; set; }
        public Nullable<bool> Mujeremb { get; set; }
        public Nullable<bool> MadreEt { get; set; }
        public Nullable<bool> Postnatal { get; set; }
        public Nullable<bool> Cuidador6meses { get; set; }
        public Nullable<bool> Cuidador6a12meses { get; set; }
        public Nullable<bool> Cuidador1a4anios { get; set; }
        public Nullable<bool> Cuidador5a9anios { get; set; }
        public Nullable<bool> C10a19anios { get; set; }
        public Nullable<bool> C20a59anios { get; set; }
        public Nullable<bool> C60anios { get; set; }
        public Nullable<bool> SeCompleta { get; set; }
        public Nullable<bool> SinCompletar { get; set; }
        public Nullable<bool> ReforzarParte { get; set; }
        public Nullable<bool> ReforzarToda { get; set; }
        public Nullable<bool> Rechazo { get; set; }
        public string Clave_hc_px { get; set; }
        public int Id_Paciente { get; set; }
    }
}
