//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CUS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hc_NUT_EtapaCambio
    {
        public int Id { get; set; }
        public string Viene { get; set; }
        public string DeseaLograr { get; set; }
        public Nullable<bool> Precontemplacion { get; set; }
        public Nullable<bool> Contemplacion { get; set; }
        public Nullable<bool> Preparacion { get; set; }
        public Nullable<bool> Mantenimiento { get; set; }
        public Nullable<bool> Terminacion { get; set; }
        public string Clave_hc_px { get; set; }
        public int Id_Paciente { get; set; }
    }
}
