//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CUS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hc_NUT_Recordatorio
    {
        public int Id { get; set; }
        public string Desayuno_Hora { get; set; }
        public string Desayuno_Preparacion { get; set; }
        public string Desayuno_Alimento { get; set; }
        public string Desayuno_Cantidad { get; set; }
        public string ColacionDes_Hora { get; set; }
        public string ColacionDes_Preparacion { get; set; }
        public string ColacionDes_Alimento { get; set; }
        public string ColacionDes_Cantidad { get; set; }
        public string Comida_Hora { get; set; }
        public string Comida_Preparacion { get; set; }
        public string Comida_Alimento { get; set; }
        public string Comida_Cantidad { get; set; }
        public string ColacionCom_Hora { get; set; }
        public string ColacionCom_Preparacion { get; set; }
        public string ColacionCom_Alimento { get; set; }
        public string ColacionCom_Cantidad { get; set; }
        public string Cena_Hora { get; set; }
        public string Cena_Preparacion { get; set; }
        public string Cena_Alimento { get; set; }
        public string Cena_Cantidad { get; set; }
        public string Clave_hc_px { get; set; }
        public int Id_Paciente { get; set; }
    }
}
