//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CUS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hc_NUT_DatosDieteticos
    {
        public int Id { get; set; }
        public string Comidas { get; set; }
        public Nullable<bool> Desayuno { get; set; }
        public Nullable<bool> Comidas2 { get; set; }
        public Nullable<bool> Cena { get; set; }
        public Nullable<bool> ColacionMat { get; set; }
        public Nullable<bool> ColacionVes { get; set; }
        public string TiempoConsumir { get; set; }
        public string Suplementos { get; set; }
        public string Especifica_Supl { get; set; }
        public string AlimentosDisgustan { get; set; }
        public string AlimentosFavoritos { get; set; }
        public string ConsumoAgua { get; set; }
        public string Especifica_ConsumoAgua { get; set; }
        public string HorasSuenio { get; set; }
        public string ActividadFisica { get; set; }
        public string Tipo_ActividadFisica { get; set; }
        public string Tiempo_ActividadFisica { get; set; }
        public string Frec_ActividadFisica { get; set; }
        public string Clave_hc_px { get; set; }
        public int Id_Paciente { get; set; }
    }
}
