//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CUS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HC_Nutricion : DbContext
    {
        public HC_Nutricion()
            : base("name=HC_Nutricion")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<hc_NUT_AlimentacionInicial> hc_NUT_AlimentacionInicial { get; set; }
        public virtual DbSet<hc_NUT_DatosDieteticos> hc_NUT_DatosDieteticos { get; set; }
        public virtual DbSet<hc_NUT_EtapaCambio> hc_NUT_EtapaCambio { get; set; }
        public virtual DbSet<hc_NUT_EvaluacionAntro> hc_NUT_EvaluacionAntro { get; set; }
        public virtual DbSet<hc_NUT_FrecuenciaAlimen> hc_NUT_FrecuenciaAlimen { get; set; }
        public virtual DbSet<hc_NUT_ImpresionDiag> hc_NUT_ImpresionDiag { get; set; }
        public virtual DbSet<hc_NUT_Otros> hc_NUT_Otros { get; set; }
        public virtual DbSet<hc_NUT_Plan> hc_NUT_Plan { get; set; }
        public virtual DbSet<hc_NUT_Pronostico> hc_NUT_Pronostico { get; set; }
        public virtual DbSet<hc_NUT_Recordatorio> hc_NUT_Recordatorio { get; set; }
        public virtual DbSet<hc_NUT_ResultadoLab> hc_NUT_ResultadoLab { get; set; }
        public virtual DbSet<hc_NUT_EducacionInicial> hc_NUT_EducacionInicial { get; set; }
        public virtual DbSet<hc_ODO_AntecedentesObs> hc_ODO_AntecedentesObs { get; set; }
        public virtual DbSet<hc_ODO_EvaluacionFuncional> hc_ODO_EvaluacionFuncional { get; set; }
        public virtual DbSet<hc_ODO_Habitos> hc_ODO_Habitos { get; set; }
        public virtual DbSet<hc_ODO_HistoriaDental> hc_ODO_HistoriaDental { get; set; }
        public virtual DbSet<hc_ODO_ImpresionDiag> hc_ODO_ImpresionDiag { get; set; }
        public virtual DbSet<hc_ODO_InformacionPeri> hc_ODO_InformacionPeri { get; set; }
        public virtual DbSet<hc_ODO_Otros> hc_ODO_Otros { get; set; }
        public virtual DbSet<hc_ODO_Plan> hc_ODO_Plan { get; set; }
        public virtual DbSet<hc_ODO_Pronostico> hc_ODO_Pronostico { get; set; }
        public virtual DbSet<hc_ODO_ResultadoLaboratorio> hc_ODO_ResultadoLaboratorio { get; set; }
        public virtual DbSet<hc_ODO_Riesgo> hc_ODO_Riesgo { get; set; }
        public virtual DbSet<hc_ODO_Odontograma> hc_ODO_Odontograma { get; set; }
    }
}
