//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CUS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hc_NUT_EvaluacionAntro
    {
        public int Id { get; set; }
        public string S4Anios_PesoN { get; set; }
        public string S4Anios_TallaN { get; set; }
        public string S4Anios_PesoA { get; set; }
        public string S4Anios_TallaA { get; set; }
        public string S4Tabla_MedPeso { get; set; }
        public string S4Tabla_MedTalla { get; set; }
        public string S4Tabla_MedPeTa { get; set; }
        public string S4Tabla_MedPeId { get; set; }
        public string S4Tabla_DesPeso { get; set; }
        public string S4Tabla_DesTalla { get; set; }
        public string S4Tabla_DesPeTa { get; set; }
        public string S4Tabla_DesPeId { get; set; }
        public string S4Tabla_RanPeso { get; set; }
        public string S4Tabla_RanTalla { get; set; }
        public string S4Tabla_RanPeTa { get; set; }
        public string S4Tabla_RanPeId { get; set; }
        public string S4Tabla_ClaPeso { get; set; }
        public string S4Tabla_ClaTalla { get; set; }
        public string S4Tabla_ClaPeTa { get; set; }
        public string S4Tabla_ClaPeId { get; set; }
        public string S4Anios_Interpretacion { get; set; }
        public string S4Anios_Observaciones { get; set; }
        public string S5Anios_PesoA { get; set; }
        public string S5Anios_TallaA { get; set; }
        public string S5Anios_Indice { get; set; }
        public string S5Anios_Desviacion { get; set; }
        public string S5Anios_Diagnostico { get; set; }
        public string S5Anios_PesoId { get; set; }
        public string S5Anios_Circunf { get; set; }
        public string S5Anios_Percentil { get; set; }
        public string S5Anios_Interpretacion { get; set; }
        public string S5Anios_Observaciones { get; set; }
        public string S10Anios_PesoA { get; set; }
        public string S10Anios_TallaA { get; set; }
        public string S10Anios_Indice { get; set; }
        public string S10Anios_Desviacion { get; set; }
        public string S10Anios_Diagnostico { get; set; }
        public string S10Anios_PesoId { get; set; }
        public string S10Anios_Circunf { get; set; }
        public string S10Anios_Percentil { get; set; }
        public string S10Anios_Interpretacion { get; set; }
        public string S10Anios_Observaciones { get; set; }
        public string S20Anios_PesoA { get; set; }
        public string S20Anios_TallaA { get; set; }
        public string S20Anios_Indice { get; set; }
        public string S20Anios_Diagnostico { get; set; }
        public string S20Anios_CircunfMu { get; set; }
        public string S20Anios_Complexion { get; set; }
        public string S20Anios_PesoId { get; set; }
        public string S20Anios_CircunfCin { get; set; }
        public string S20Anios_CircunfCad { get; set; }
        public string S20Anios_IndiceCin { get; set; }
        public string S20Anios_Riesgo { get; set; }
        public string S20Anios_Observaciones { get; set; }
        public string S60Anios_PesoA { get; set; }
        public string S60Anios_TallaA { get; set; }
        public string S60Anios_Indice { get; set; }
        public string S60Anios_Diagnostico { get; set; }
        public string S60Anios_CircunfMu { get; set; }
        public string S60Anios_Complexion { get; set; }
        public string S60Anios_PesoId { get; set; }
        public string S60Anios_PesoAj { get; set; }
        public string S60Anios_CircunfCin { get; set; }
        public string S60Anios_CircunfCad { get; set; }
        public string S60Anios_IndiceCin { get; set; }
        public string S60Anios_CircunfBra { get; set; }
        public string S60Anios_CircunfPan { get; set; }
        public string S60Anios_Observaciones { get; set; }
        public string SEmbaraz_PesoA { get; set; }
        public string SEmbaraz_TallaA { get; set; }
        public string SEmbaraz_Gestacion { get; set; }
        public string SEmbaraz_CircunfBra { get; set; }
        public string SEmbaraz_PesoPreges { get; set; }
        public string SEmbaraz_Indice { get; set; }
        public string SEmbaraz_Diagnostico { get; set; }
        public string SEmbaraz_GanPesoDesd { get; set; }
        public string SEmbaraz_GanPesoAct { get; set; }
        public string SEmbaraz_Observaciones { get; set; }
        public string Clave_hc_px { get; set; }
        public int Id_Paciente { get; set; }
    }
}
