//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CUS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hc_NUT_FrecuenciaAlimen
    {
        public int Id { get; set; }
        public Nullable<bool> Leche { get; set; }
        public string Frecuencia_Leche { get; set; }
        public Nullable<bool> Verdura { get; set; }
        public string Frecuencia_Verdura { get; set; }
        public Nullable<bool> Fruta { get; set; }
        public string Frecuencia_Fruta { get; set; }
        public Nullable<bool> Cereales { get; set; }
        public string Frecuencia_Cereales { get; set; }
        public Nullable<bool> Leguminosas { get; set; }
        public string Frecuencia_Leguminosas { get; set; }
        public Nullable<bool> Carne { get; set; }
        public string Frecuencia_Carne { get; set; }
        public Nullable<bool> Grasa { get; set; }
        public string Frecuencia_Grasa { get; set; }
        public Nullable<bool> Azucar { get; set; }
        public string Frecuencia_Azucar { get; set; }
        public Nullable<bool> BebidasAzucar { get; set; }
        public string Frecuencia_BebidasAzucar { get; set; }
        public Nullable<bool> BebidasAlt { get; set; }
        public string Frecuencia_BebidasAlt { get; set; }
        public Nullable<bool> Cafe { get; set; }
        public string Frecuencia_Cafe { get; set; }
        public Nullable<bool> Te { get; set; }
        public string Frecuencia_Te { get; set; }
        public Nullable<bool> Cerveza { get; set; }
        public string Frecuencia_Cerveza { get; set; }
        public Nullable<bool> ProductosPan { get; set; }
        public string Frecuencia_ProductosPan { get; set; }
        public Nullable<bool> Confiteria { get; set; }
        public string Frecuencia_Confiteria { get; set; }
        public Nullable<bool> Embutidos { get; set; }
        public string Frecuencia_Embutidos { get; set; }
        public Nullable<bool> AlimentosEnla { get; set; }
        public string Frecuencia_AlimentosEnla { get; set; }
        public Nullable<bool> Sopas { get; set; }
        public string Frecuencia_Sopas { get; set; }
        public Nullable<bool> Verduras { get; set; }
        public string Frecuencia_Verduras { get; set; }
        public Nullable<bool> ComidaRap { get; set; }
        public string Frecuencia_ComidaRap { get; set; }
        public Nullable<bool> ComidaGras { get; set; }
        public string Frecuencia_ComidaGras { get; set; }
        public Nullable<bool> ProductosChat { get; set; }
        public string Frecuencia_ProductosChat { get; set; }
        public Nullable<bool> Consome { get; set; }
        public string Frecuencia_Consome { get; set; }
        public Nullable<bool> Sal { get; set; }
        public string Frecuencia_Sal { get; set; }
        public Nullable<bool> Sucedaneo { get; set; }
        public string Frecuencia_Sucedaneo { get; set; }
        public Nullable<bool> Otros { get; set; }
        public string Frecuencia_Otros { get; set; }
        public string Clave_hc_px { get; set; }
        public int Id_Paciente { get; set; }
    }
}
