//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CUS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hc_ODO_Habitos
    {
        public int Id { get; set; }
        public string ConsCarbohidratosODO { get; set; }
        public string AlimEntreComidasODO { get; set; }
        public string Especifica_AlimEntreComidasODO { get; set; }
        public string HigieneOralODO { get; set; }
        public string Frecuencia_HigieneOralODO { get; set; }
        public Nullable<bool> Solo_HigieneOralODO { get; set; }
        public Nullable<bool> ConAyuda_HigieneOralODO { get; set; }
        public string TipoCepillo_HigieneOralODO { get; set; }
        public string TipoPasta_HigieneOralODO { get; set; }
        public Nullable<bool> SuccionLabialODO { get; set; }
        public Nullable<bool> MorderObjetosODO { get; set; }
        public Nullable<bool> RespiracionOralODO { get; set; }
        public Nullable<bool> SuccionDigitalODO { get; set; }
        public Nullable<bool> OnicofagiaODO { get; set; }
        public Nullable<bool> BruxismoODO { get; set; }
        public Nullable<bool> BiberonODO { get; set; }
        public Nullable<bool> ChuponODO { get; set; }
        public string Clave_hc_px { get; set; }
        public int Id_Paciente { get; set; }
    }
}
