//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CUS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hc_ODO_Odontograma
    {
        public int Id { get; set; }
        public string MasticaDientesODO { get; set; }
        public Nullable<bool> CheckBox18 { get; set; }
        public string Input18 { get; set; }
        public Nullable<bool> CheckBox17 { get; set; }
        public string Input17 { get; set; }
        public Nullable<bool> CheckBox16 { get; set; }
        public string Input16 { get; set; }
        public Nullable<bool> CheckBox15 { get; set; }
        public string Input15 { get; set; }
        public Nullable<bool> CheckBox14 { get; set; }
        public string Input14 { get; set; }
        public Nullable<bool> CheckBox13 { get; set; }
        public string Input13 { get; set; }
        public Nullable<bool> CheckBox12 { get; set; }
        public string Input12 { get; set; }
        public Nullable<bool> CheckBox11 { get; set; }
        public string Input11 { get; set; }
        public Nullable<bool> CheckBox21 { get; set; }
        public string Input21 { get; set; }
        public Nullable<bool> CheckBox22 { get; set; }
        public string Input22 { get; set; }
        public Nullable<bool> CheckBox23 { get; set; }
        public string Input23 { get; set; }
        public Nullable<bool> CheckBox24 { get; set; }
        public string Input24 { get; set; }
        public Nullable<bool> CheckBox25 { get; set; }
        public string Input25 { get; set; }
        public Nullable<bool> CheckBox26 { get; set; }
        public string Input26 { get; set; }
        public Nullable<bool> CheckBox27 { get; set; }
        public string Input27 { get; set; }
        public Nullable<bool> CheckBox28 { get; set; }
        public string Input28 { get; set; }
        public Nullable<bool> CheckBox55 { get; set; }
        public string Input55 { get; set; }
        public Nullable<bool> CheckBox54 { get; set; }
        public string Input54 { get; set; }
        public Nullable<bool> CheckBox53 { get; set; }
        public string Input53 { get; set; }
        public Nullable<bool> CheckBox52 { get; set; }
        public string Input52 { get; set; }
        public Nullable<bool> CheckBox51 { get; set; }
        public string Input51 { get; set; }
        public Nullable<bool> CheckBox61 { get; set; }
        public string Input61 { get; set; }
        public Nullable<bool> CheckBox62 { get; set; }
        public string Input62 { get; set; }
        public Nullable<bool> CheckBox63 { get; set; }
        public string Input63 { get; set; }
        public Nullable<bool> CheckBox64 { get; set; }
        public string Input64 { get; set; }
        public Nullable<bool> CheckBox65 { get; set; }
        public string Input65 { get; set; }
        public Nullable<bool> CheckBox85 { get; set; }
        public string Input85 { get; set; }
        public Nullable<bool> CheckBox84 { get; set; }
        public string Input84 { get; set; }
        public Nullable<bool> CheckBox83 { get; set; }
        public string Input83 { get; set; }
        public Nullable<bool> CheckBox82 { get; set; }
        public string Input82 { get; set; }
        public Nullable<bool> CheckBox81 { get; set; }
        public string Input81 { get; set; }
        public Nullable<bool> CheckBox71 { get; set; }
        public string Input71 { get; set; }
        public Nullable<bool> CheckBox72 { get; set; }
        public string Input72 { get; set; }
        public Nullable<bool> CheckBox73 { get; set; }
        public string Input73 { get; set; }
        public Nullable<bool> CheckBox74 { get; set; }
        public string Input74 { get; set; }
        public Nullable<bool> CheckBox75 { get; set; }
        public string Input75 { get; set; }
        public Nullable<bool> CheckBox48 { get; set; }
        public string Input48 { get; set; }
        public Nullable<bool> CheckBox47 { get; set; }
        public string Input47 { get; set; }
        public Nullable<bool> CheckBox46 { get; set; }
        public string Input46 { get; set; }
        public Nullable<bool> CheckBox45 { get; set; }
        public string Input45 { get; set; }
        public Nullable<bool> CheckBox44 { get; set; }
        public string Input44 { get; set; }
        public Nullable<bool> CheckBox43 { get; set; }
        public string Input43 { get; set; }
        public Nullable<bool> CheckBox42 { get; set; }
        public string Input42 { get; set; }
        public Nullable<bool> CheckBox41 { get; set; }
        public string Input41 { get; set; }
        public Nullable<bool> CheckBox31 { get; set; }
        public string Input31 { get; set; }
        public Nullable<bool> CheckBox32 { get; set; }
        public string Input32 { get; set; }
        public Nullable<bool> CheckBox33 { get; set; }
        public string Input33 { get; set; }
        public Nullable<bool> CheckBox34 { get; set; }
        public string Input34 { get; set; }
        public Nullable<bool> CheckBox35 { get; set; }
        public string Input35 { get; set; }
        public Nullable<bool> CheckBox36 { get; set; }
        public string Input36 { get; set; }
        public Nullable<bool> CheckBox37 { get; set; }
        public string Input37 { get; set; }
        public Nullable<bool> CheckBox38 { get; set; }
        public string Input38 { get; set; }
        public Nullable<bool> AltaODO { get; set; }
        public Nullable<bool> MediaODO { get; set; }
        public Nullable<bool> BajaODO { get; set; }
        public string Clave_hc_px { get; set; }
        public int Id_Paciente { get; set; }
    }
}
