//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CUS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hc_ODO_InformacionPeri
    {
        public int Id { get; set; }
        public string EmbarazoTerminoODO { get; set; }
        public string Motivo_EmbarazoTerODO { get; set; }
        public string CompEmbarazoODO { get; set; }
        public string PesoNacerODO { get; set; }
        public string EstaturaNacerODO { get; set; }
        public string TipoLactanciaODO { get; set; }
        public string TiempoLactanciaODO { get; set; }
        public string MostroCartillaODO { get; set; }
        public string EsquemaCompletoODO { get; set; }
        public string Especifica_EsquemaComODO { get; set; }
        public string Clave_hc_px { get; set; }
        public int Id_Paciente { get; set; }
    }
}
