//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CUS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hc_ODO_HistoriaDental
    {
        public int Id { get; set; }
        public string PrimeraVisitaODO { get; set; }
        public string TratamientosRealizadoaODO { get; set; }
        public string FamiliarPadecidoODO { get; set; }
        public string GolpeadoDientesODO { get; set; }
        public string Especifica_GolpeadoDienODO { get; set; }
        public string PacienteCooperoODO { get; set; }
        public string InteresConservarDienODO { get; set; }
        public string SatisfechoODO { get; set; }
        public string Especifica_SatisfechoODO { get; set; }
        public string Clave_hc_px { get; set; }
        public int Id_Paciente { get; set; }
    }
}
