//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CUS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hc_ODO_EvaluacionFuncional
    {
        public int Id { get; set; }
        public Nullable<bool> FA_Sup_Redondo { get; set; }
        public Nullable<bool> FA_Sup_Triangular { get; set; }
        public Nullable<bool> FA_Sup_Cuadrado { get; set; }
        public Nullable<bool> FA_Inf_Redondo { get; set; }
        public Nullable<bool> FA_Inf_Triangular { get; set; }
        public Nullable<bool> FA_Inf_Cuadrado { get; set; }
        public Nullable<bool> FA_MA_Anterior { get; set; }
        public Nullable<bool> FA_MA_Posterior { get; set; }
        public Nullable<bool> FA_MA_NoAplica { get; set; }
        public Nullable<bool> FA_MC_Anterior { get; set; }
        public Nullable<bool> FA_MC_Posterior { get; set; }
        public Nullable<bool> FA_MC_NoAplica { get; set; }
        public Nullable<bool> SMI_Der_EscalonM { get; set; }
        public Nullable<bool> SMI_Der_EscalonD { get; set; }
        public Nullable<bool> SMI_Der_PlanoRecto { get; set; }
        public Nullable<bool> SMI_Der_NoAplica { get; set; }
        public Nullable<bool> SMI_Izq_EscalonM { get; set; }
        public Nullable<bool> SMI_Izq_EscalonD { get; set; }
        public Nullable<bool> SMI_Izq_PlanoRecto { get; set; }
        public Nullable<bool> SMI_Izq_NoAplica { get; set; }
        public Nullable<bool> CPri_Der_ClaseI { get; set; }
        public Nullable<bool> CPri_Der_ClaseII { get; set; }
        public Nullable<bool> CPri_Der_ClaseIII { get; set; }
        public Nullable<bool> CPri_Der_NoAplica { get; set; }
        public Nullable<bool> CPri_Izq_ClaseI { get; set; }
        public Nullable<bool> CPri_Izq_ClaseII { get; set; }
        public Nullable<bool> CPri_Izq_ClaseIII { get; set; }
        public Nullable<bool> CPri_Izq_NoAplica { get; set; }
        public Nullable<bool> PMP_Der_ClaseI { get; set; }
        public Nullable<bool> PMP_Der_ClaseII { get; set; }
        public Nullable<bool> PMP_Der_ClaseIII { get; set; }
        public Nullable<bool> PMP_Der_NoAplica { get; set; }
        public Nullable<bool> PMP_Izq_ClaseI { get; set; }
        public Nullable<bool> PMP_Izq_ClaseII { get; set; }
        public Nullable<bool> PMP_Izq_ClaseIII { get; set; }
        public Nullable<bool> PMP_Izq_NoAplica { get; set; }
        public Nullable<bool> CPer_Der_ClaseI { get; set; }
        public Nullable<bool> CPer_Der_ClaseII { get; set; }
        public Nullable<bool> CPer_Der_ClaseIII { get; set; }
        public Nullable<bool> CPer_Der_NoAplica { get; set; }
        public Nullable<bool> CPer_Izq_ClaseI { get; set; }
        public Nullable<bool> CPer_Izq_ClaseII { get; set; }
        public Nullable<bool> CPer_Izq_ClaseIII { get; set; }
        public Nullable<bool> CPer_Izq_NoAplica { get; set; }
        public string Clave_hc_px { get; set; }
        public int Id_Paciente { get; set; }
    }
}
