//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CUS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hc_PS_DiagnosticoPres
    {
        public int Id { get; set; }
        public string diagnostico1 { get; set; }
        public string diagnostico2 { get; set; }
        public string diagnostico3 { get; set; }
        public string diagnostico4 { get; set; }
        public string diagnostico5 { get; set; }
        public Nullable<bool> LigadoEvolucion { get; set; }
        public Nullable<bool> Favorable { get; set; }
        public Nullable<bool> Desfavorable { get; set; }
        public int Id_Paciente { get; set; }
        public string Clave_hc_px { get; set; }
    }
}
