//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CUS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hc_PS_SintomatologiaActual
    {
        public int Id { get; set; }
        public string Sintomatologia { get; set; }
        public Nullable<bool> DificultadRespirar_Si { get; set; }
        public Nullable<bool> DificultadRespirar_No { get; set; }
        public string DificultadRespirar_Esp { get; set; }
        public Nullable<bool> SensacionMorir_Si { get; set; }
        public Nullable<bool> SensacionMorir_No { get; set; }
        public string SensacionMorir_Esp { get; set; }
        public Nullable<bool> TemblorCuerpo_Si { get; set; }
        public Nullable<bool> TemblorCuerpo_No { get; set; }
        public string TemblorCuerpo_Esp { get; set; }
        public Nullable<bool> Desmayo_Si { get; set; }
        public Nullable<bool> Desmayo_No { get; set; }
        public string Desmayo_Esp { get; set; }
        public Nullable<bool> Lloras_Si { get; set; }
        public Nullable<bool> Lloras_No { get; set; }
        public string Lloras_Esp { get; set; }
        public Nullable<bool> DespiertasAnimo_Si { get; set; }
        public Nullable<bool> DespiertasAnimo_No { get; set; }
        public string DespiertasAnimo_Esp { get; set; }
        public Nullable<bool> Culpable_Si { get; set; }
        public Nullable<bool> Culpable_No { get; set; }
        public string Culpable_Esp { get; set; }
        public Nullable<bool> PerdidoMotivacion_Si { get; set; }
        public Nullable<bool> PerdidoMotivacion_No { get; set; }
        public string PerdidoMotivacion_Esp { get; set; }
        public Nullable<bool> QuererMorir_Si { get; set; }
        public Nullable<bool> QuererMorir_No { get; set; }
        public string QuererMorir_Esp { get; set; }
        public Nullable<bool> Consultado_Si { get; set; }
        public Nullable<bool> Consultado_No { get; set; }
        public string Consultado_Esp { get; set; }
        public Nullable<bool> ProblemasAtencion_Si { get; set; }
        public Nullable<bool> ProblemasAtencion_No { get; set; }
        public string ProblemasAtencion_Esp { get; set; }
        public Nullable<bool> ProblemasDormir_Si { get; set; }
        public Nullable<bool> ProblemasDormir_No { get; set; }
        public string ProblemasDormir_Esp { get; set; }
        public Nullable<bool> CambioApetito_Si { get; set; }
        public Nullable<bool> CambioApetito_No { get; set; }
        public string CambioApetito_Esp { get; set; }
        public Nullable<bool> ParteTiempo_Triste { get; set; }
        public Nullable<bool> ParteTiempo_Enojado { get; set; }
        public Nullable<bool> ParteTiempo_Miedo { get; set; }
        public Nullable<bool> ParteTiempo_Angustiado { get; set; }
        public Nullable<bool> ParteTiempo_Estresado { get; set; }
        public Nullable<bool> ParteTiempo_Maniaco { get; set; }
        public Nullable<bool> ParteTiempo_Otra { get; set; }
        public string ParteTiempo_OtraEsp { get; set; }
        public int Id_Paciente { get; set; }
        public string Clave_hc_px { get; set; }
    }
}
