//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CUS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hc_SignosVitales
    {
        public int id { get; set; }
        public string expediente { get; set; }
        public string usuario { get; set; }
        public string escala_dolor { get; set; }
        public Nullable<float> peso { get; set; }
        public Nullable<float> talla { get; set; }
        public Nullable<float> temperatura { get; set; }
        public Nullable<float> fresp { get; set; }
        public Nullable<float> fcard { get; set; }
        public Nullable<float> ta1 { get; set; }
        public Nullable<float> ta2 { get; set; }
        public Nullable<float> dstx { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string ip_realiza { get; set; }
        public Nullable<int> Id_Paciente { get; set; }
        public string Clave_hc_px { get; set; }
    }
}
