//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CUS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hc_valores_creencias
    {
        public int Id { get; set; }
        public string perteneceReligion { get; set; }
        public string religion { get; set; }
        public string EspecifiqueReligion { get; set; }
        public string creenciaReligiosa { get; set; }
        public string EspecifiqueCreencia { get; set; }
        public string costumbreValores { get; set; }
        public string EspecifiqueCostumbres { get; set; }
        public int Id_Paciente { get; set; }
        public Nullable<int> Id_HistoriaClinica { get; set; }
        public string Clave_hc_px { get; set; }
    
        public virtual Paciente Paciente { get; set; }
    }
}
