//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CUS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hc_valoracion_familiar
    {
        public int Id { get; set; }
        public string mamaPaciente { get; set; }
        public string EdadMama { get; set; }
        public string GradoMama { get; set; }
        public string OcupacionMama { get; set; }
        public string TipoTrabajoMama { get; set; }
        public string papaPaciente { get; set; }
        public string EdadPapa { get; set; }
        public string GradoPapa { get; set; }
        public string OcupacionPapa { get; set; }
        public string TipoTrabajoPapa { get; set; }
        public string ViveCon { get; set; }
        public string tieneHermanos { get; set; }
        public Nullable<int> CuantosHermanos { get; set; }
        public string EspecifiqueEnf { get; set; }
        public string involucraTratamiento { get; set; }
        public string EspecifiqueInvol { get; set; }
        public string riesgoSocial { get; set; }
        public int Id_Paciente { get; set; }
        public Nullable<int> Id_HistoriaClinica { get; set; }
        public string Clave_hc_px { get; set; }
    
        public virtual Paciente Paciente { get; set; }
    }
}
