//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CUS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotaEvolucion
    {
        public int id { get; set; }
        public string num_exp { get; set; }
        public string medico { get; set; }
        public string nota_subjetivo { get; set; }
        public string nota_objetivo { get; set; }
        public string nota_plan { get; set; }
        public string diagnostico1 { get; set; }
        public string diagnostico2 { get; set; }
        public string diagnostico3 { get; set; }
        public string diagnostico4 { get; set; }
        public string diagnostico5 { get; set; }
        public string tipo_diagnostico1 { get; set; }
        public string tipo_diagnostico2 { get; set; }
        public string tipo_diagnostico3 { get; set; }
        public string tipo_diagnostico4 { get; set; }
        public string tipo_diagnostico5 { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string ip_realiza { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> id_unidad { get; set; }
    }
}
