//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CUS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paciente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Paciente()
        {
            this.hc_antecedentes_desarrollo = new HashSet<hc_antecedentes_desarrollo>();
            this.hc_antecedentes_ginecoobstetricos = new HashSet<hc_antecedentes_ginecoobstetricos>();
            this.hc_antecedentes_perinatales = new HashSet<hc_antecedentes_perinatales>();
            this.hc_evaluacion_economica = new HashSet<hc_evaluacion_economica>();
            this.hc_evaluacion_social = new HashSet<hc_evaluacion_social>();
            this.hc_factores_riesgo_psicologicos = new HashSet<hc_factores_riesgo_psicologicos>();
            this.hc_ficha_identificacion = new HashSet<hc_ficha_identificacion>();
            this.hc_habitos = new HashSet<hc_habitos>();
            this.hc_historial_consumo = new HashSet<hc_historial_consumo>();
            this.hc_inmunizaciones = new HashSet<hc_inmunizaciones>();
            this.hc_valoracion_familiar = new HashSet<hc_valoracion_familiar>();
            this.hc_valores_creencias = new HashSet<hc_valores_creencias>();
            this.HistoriaClinica = new HashSet<HistoriaClinica>();
            this.hc_alimentacion = new HashSet<hc_alimentacion>();
            this.hc_antecedentes_patologicos = new HashSet<hc_antecedentes_patologicos>();
            this.hc_interrogatorio = new HashSet<hc_interrogatorio>();
            this.hc_riesgo_caidas = new HashSet<hc_riesgo_caidas>();
            this.hc_exploracion_fisica = new HashSet<hc_exploracion_fisica>();
        }
    
        public int Id { get; set; }
        public int UnidadAfiliacion { get; set; }
        public string CURP { get; set; }
        public string Nombre { get; set; }
        public string PrimerApellido { get; set; }
        public string SegundoApellido { get; set; }
        public string Sexo { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public string Nacionalidad { get; set; }
        public string EntidadNacimiento { get; set; }
        public int Edad { get; set; }
        public string Expediente { get; set; }
        public string Dir_Calle { get; set; }
        public int Dir_Numero { get; set; }
        public int Dir_CP { get; set; }
        public string Dir_Colonia { get; set; }
        public string Dir_Municipio { get; set; }
        public string Dir_EntidadFed { get; set; }
        public string Telefono1 { get; set; }
        public string Telefono2 { get; set; }
        public string Email { get; set; }
        public string RFC { get; set; }
        public string EstadoCivil { get; set; }
        public string Escolaridad { get; set; }
        public string Ocupacion { get; set; }
        public string ServicioSalud { get; set; }
        public string ServicioSalud_Extra { get; set; }
        public bool DE_Indigena { get; set; }
        public bool DE_Migrante { get; set; }
        public bool DE_Afroamericano { get; set; }
        public bool BA_Visual { get; set; }
        public bool BA_Auditiva { get; set; }
        public bool BA_Fisica { get; set; }
        public bool BA_Mental { get; set; }
        public bool BA_Idioma { get; set; }
        public string BA_Idioma_Nombre { get; set; }
        public bool BA_Analfabeta { get; set; }
        public string CE_Nombre { get; set; }
        public string CE_Calle { get; set; }
        public int CE_Numero { get; set; }
        public int CE_CP { get; set; }
        public string CE_Colonia { get; set; }
        public string CE_Municipio { get; set; }
        public string CE_EntidadFed { get; set; }
        public string CE_Telefono { get; set; }
        public string Nombre_Tutor { get; set; }
        public string PrimerApellido_Tutor { get; set; }
        public string SegundoApellido_Tutor { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public string Curp_Calculado { get; set; }
        public string Curp_CalculadoMotivo { get; set; }
        public Nullable<bool> NA_DE { get; set; }
        public Nullable<bool> NA_BA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hc_antecedentes_desarrollo> hc_antecedentes_desarrollo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hc_antecedentes_ginecoobstetricos> hc_antecedentes_ginecoobstetricos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hc_antecedentes_perinatales> hc_antecedentes_perinatales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hc_evaluacion_economica> hc_evaluacion_economica { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hc_evaluacion_social> hc_evaluacion_social { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hc_factores_riesgo_psicologicos> hc_factores_riesgo_psicologicos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hc_ficha_identificacion> hc_ficha_identificacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hc_habitos> hc_habitos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hc_historial_consumo> hc_historial_consumo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hc_inmunizaciones> hc_inmunizaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hc_valoracion_familiar> hc_valoracion_familiar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hc_valores_creencias> hc_valores_creencias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoriaClinica> HistoriaClinica { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hc_alimentacion> hc_alimentacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hc_antecedentes_patologicos> hc_antecedentes_patologicos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hc_interrogatorio> hc_interrogatorio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hc_riesgo_caidas> hc_riesgo_caidas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hc_exploracion_fisica> hc_exploracion_fisica { get; set; }
    }
}
