//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CUS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PacienteCopia
    {
        public int Id { get; set; }
        public Nullable<int> Id_Paciente { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
    }
}
