//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CUS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SignosVitales
    {
        public int id { get; set; }
        public string expediente { get; set; }
        public string usuario { get; set; }
        public string escala_dolor { get; set; }
        public Nullable<int> peso { get; set; }
        public Nullable<int> talla { get; set; }
        public Nullable<int> temperatura { get; set; }
        public Nullable<int> fresp { get; set; }
        public Nullable<int> fcard { get; set; }
        public Nullable<int> ta1 { get; set; }
        public Nullable<int> ta2 { get; set; }
        public Nullable<int> dstx { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string ip_realiza { get; set; }
    }
}
